aragonone/court-backend

- packages/cli/bin/airdrop.js
- packages/cli/bin/setup.js
- packages/cli/package.json
- packages/cli/src/commands/activate.js
- packages/shared/models/Court.js
> CLI: Implement airdrop script

- packages/cli/src/commands/reveal.js
- packages/server/src/controllers/RevealsController.js
- packages/server/src/models/Reveal.js
- packages/server/src/validators/RevealsValidator.js
- packages/services/config.js
- packages/services/package.json
- packages/services/src/workers/heartbeat.js
- packages/services/src/workers/reveal.js
- packages/shared/models/Court.js
**MERGE AFTER #18**
Fixes #7 
This PR provides a background service in charge of reveal those automatic reveals requested by the jurors of Aragon Court
> Service: Implement reveal worker

- packages/server/src/database/migrations/20200103090553-create-settlements.js
- packages/server/src/models/Settlement.js
- packages/services/bin/worker.js
- packages/services/config.js
- packages/services/src/workers/disputes.js
- packages/services/src/workers/settle-appeals.js
- packages/services/src/workers/settle-jurors.js
- packages/services/src/workers/settle-penalties.js
- packages/services/src/workers/settlements.js
- packages/shared/models/Court.js
- packages/shared/models/evironments/Environment.js
- packages/shared/package.json
**MERGE AFTER #19**
Fixes #6 
This PR provides two background services, one in charge of collecting new disputes and another one in charge of settling them when these are ready to be settled.
> Service: Implement settlements worker

- packages/app/src/actions/jurors.js
- packages/app/src/components/jurors/JurorDetail.react.js
- packages/app/src/components/jurors/JurorsList.react.js
> App: add treeId to table in /jurors

- packages/app/src/components/jurors/JurorsList.react.js
> App: add summary to /jurors

- packages/cli/src/commands/reveal.js
When juror parameter is not provided.
> cli: Fix reveal command

- packages/shared/models/evironments/TruffleEnvironment.js
> shared: Allow to override court address with env var

- packages/shared/models/Court.js
Fixes https://github.com/aragonone/court-backend/issues/56
> CLI: Use UTF8 encoding for evidence

- .github/workflows/main.yml
- .github/workflows/server-ci-cd.yml
- .github/workflows/services-ci-cd.yml
This has already been tested and deployed using containers from my forked repository.
> Added CI/CD for server and services

- packages/server/src/index.js
> Server: Check DB connection on start

- .env.sample
- packages/server/src/database/check-connection.js
- packages/server/src/index.js
- packages/server/src/routes/index.js
> Server: Polish main entry point

- packages/app/src/actions/admin.js
- packages/app/src/components/core/PrivateRoute.react.js
- packages/app/src/store/token.js
- packages/app/src/web3/Server.js
> App: Improve local storage usage for authentication token

- .github/workflows/testnet.yml
- packages/app/README.md
> Chore: Generalize package versions for all testnets

- packages/shared/models/Court.js
We were not using the given `periods` arg actually
> CLI: Fix subscribe command

- packages/app/src/components/court/CourtConfig.react.js
**MERGE AFTER #100**
Fixes #92
> App: Show network name

- .github/workflows/mainnet.yml
- .github/workflows/testnet.yml
- removed set label to reduce service account permissions
- added set image for each testnet instance
> ci-ci fixes

- .github/workflows/mainnet.yml
- .github/workflows/testnet.yml
add sleep 10 to wait for k8s to reroute ingress
> Ci cd curl fix

- .env.sample
- packages/server/src/database/migrations/20200326212213-create-keeper-suspicious-transactions.js
- packages/server/src/models/KeeperSuspiciousTransaction.js
- packages/services/config.js
- packages/services/package.json
- packages/services/src/models/Etherscan.js
- packages/services/src/workers/monitor-keeper.js
Fixes #85 
Reducing the number of requests to Infura, we can use Etherscan for this one
> Service: Improve monitor keeper

- .github/scripts/docker-build.sh
- .github/scripts/docker-release.sh
- .github/scripts/kubectl-config.sh
- .github/scripts/kubectl-set-image.sh
- .github/scripts/kubectl-wait-ready.sh
- .github/scripts/test-server/run.sh
- .github/workflows/dashboard.yml
- .github/workflows/mainnet.yml
- .github/workflows/testnet.yml
> CI/CD: moved all ci/cd logic into shared scripts

- .github/scripts/emails-sync.sh
- .github/workflows/dashboard.yml
- .github/workflows/emails-staging.yml
- .github/workflows/emails.yml
- .github/workflows/testnet.yml
- emails/README.md
- emails/build-emails
- emails/env.js
- emails/package.json
- emails/templates/appeals-opened.js
- emails/templates/drafted.js
- emails/templates/due-tasks.js
- emails/templates/email-verification.js
- emails/templates/generic-action.js
- emails/templates/generic-notification.js
- emails/templates/generic-warning.js
- emails/templates/generic.js
- emails/templates/missed-vote.js
- emails/templates/ruled.js
- emails/yarn.lock
This takes care of syncing templates to postmark and assets to storage bucket.
I had to extend the email build command a bit. You can also execute it manually.
> Emails: automatic sync

- packages/server/src/helpers/session-middleware.js
- packages/server/src/index.js
Need to add `SameSite=None; Secure` for Chrome 80+
https://blog.chromium.org/2019/10/developers-get-ready-for-new.html
(this is not related to Brave browser problem)
> Server: samesite cookie fix

- emails/template-utils.js
- emails/templates/notification-settings-announcement.js
- packages/server/scripts/notify-new-anj-registrations.js
- packages/server/scripts/notify-unverified-anj-registrations.js
- packages/server/src/models/objection/User.js
current template render:
Email Subject: **New on Aragon Court: modify your juror notification settings from the Dashboard**
> Notifications service: Notify unverified anj registrations

- packages/app/src/actions/jurors.js
- packages/app/src/components/jurors/JurorsList.react.js
Depends on https://github.com/aragon/court-subgraph/pull/68
> App: Show jurors registry total deactivation

- Dockerfile
- docker-compose.yml
Fixes https://github.com/aragonone/court-backend/issues/138
> Chore: Minor docker enhancements

- packages/server/README.md
- packages/services/README.md
- packages/shared/README.md
Updated missing readmes for server, services and shared
> Chore: Update READMEs

- packages/server/scripts/notify-fee-mechanism-upgrade.js
- packages/server/src/models/objection/User.js
> Email: notify fee mechanism upgrade
